name: Run Integration tests
'on':
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Checkout Microservices-Demo Project
        uses: actions/checkout@v2
        with:
          repository: microservices-demo/microservices-demo
          path: microservices-demo

      - name: Run Infrastructure
        run: docker-compose -f microservices-demo/deploy/docker-compose/docker-compose.yml up -d

      - name: Checkout Test Project
        uses: actions/checkout@v2

      - name: Test
        run: ./gradlew clean test
