name: Run Integration tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: microservices-demo/microservices-demo
          path: microservices-demo

      - name: Test
        run: ls

      - name: Clone Test Project
        uses: actions/checkout@v2
        path: api-automation-draft

      - name: Test
          run: ls